version: "3.5"
services:
  mqtt:
    image: toke/mosquitto
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped
    networks:
      docker-net:
        # fix ip
        ipv4_address: 172.25.0.2
  
  api-server:
    container_name: apiserver
    expose: 
      - 8000
    ports:
      - 8000:8000
    volumes:
      - /home/<your directory>/db/dummy.csv:/app/db/dummy.csv
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - docker-net
    depends_on:
      - mqtt

networks:
  docker-net:
    driver: bridge
